version: '3.6'
services:

  php-fpm:
    image: sitegeist/neos-php-fpm:latest
    working_dir: /project
    user: ${HOST_USER}
    environment:
      - FLOW_CONTEXT=Development/Docker
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=${CRED_MYSQL_DATABASE}
      - MYSQL_USER=${CRED_MYSQL_USER}
      - MYSQL_PASSWORD=${CRED_MYSQL_PASSWORD}
      - COMPOSER_HOME=/data/composer
      - FLOW_PATH_DATA=/data/neos
    volumes:
      - composer_data:/data/composer:delegated
      - neos_data:/data/neos:delegated
      - .:/project
    secrets:
      - id_rsa.pub
      - id_rsa

  webserver:
    image: sitegeist/neos-nginx:latest
    working_dir: /project
    environment:
      - PORT_NGINX=${PORT_NGINX}
      - PROJECT_ROOT=/project
      - PHP_FPM_HOST=php-fpm
      - PHP_FPM_PORT=9000
      - FLOW_CONTEXT=Development/Docker
    volumes:
      - .:/project
    ports:
      - "${PORT_NGINX}"

  mariadb:
    image: sitegeist/neos-mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${CRED_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${CRED_MYSQL_DATABASE}
      - MYSQL_USER=${CRED_MYSQL_USER}
      - MYSQL_PASSWORD=${CRED_MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql:delegated
    ports:
      - "${PORT_MARIADB}"

  redis:
    image: sitegeist/neos-redis:latest

  testcafe:
    image: sitegeist/neos-testcafe
    entrypoint: tail -f /dev/null
    environment:
      - TEST_DOMAIN=webserver:${PORT_NGINX}
    volumes:
      - ./Test:/tests

  ###############################################################################
  #                                EXAMPLES                                     #
  ###############################################################################

  # elasticsearch:
  #   image: sitegeist/neos-elasticsearch:latest
  #  ports:
  #    - "${PORT_ELASTICSEARCH}"

volumes:
  composer_data:
  neos_data:
  database:

secrets:
  id_rsa.pub:
    file: ~/.ssh/id_rsa.pub
  id_rsa:
    file: ~/.ssh/id_rsa
