Neos:
  Imagine:
    driver: Imagick
  Flow:
    persistence:
      backendOptions:
        host: '%env:MYSQL_HOST%'
        dbname: '%env:MYSQL_DATABASE%'
        user: '%env:MYSQL_USER%'
        password: '%env:MYSQL_PASSWORD%'
#Flowpack:
#  ElasticSearch:
#    clients:
#      default:
#        -
#          host: elasticsearch
#          port: 9200
#          username: ''
#          password: ''